### ISSUE TITLE
Feature request: Merging with another custom icons repository

### ISSUE THREAD

**Issue by kaizersoje** [Mariusthvdb/custom-icons#47]
Firstly, I appreciate all the work you and the other authors have done on creating the custom icons.

There is another [repository ](https://github.com/elax46/custom-brand-icons) that contains a large number of custom icons. I was wondering if the icons from here could be added to that repository so that as an user, I can refer to one repository for all custom icons :)

**Comment by arallsopp** [comment]
One of the reasons I would not support that is that the repo you've linked steals icons without credit. 

That kind of behaviour damages the community and works against content creators and users.

**Comment by kaizersoje** [comment]
Well, I would not condone such behaviour either. However, I can see a "Thanks" section in that repository. I would expect that any icons added are properly credited to their authors.

**Comment by arallsopp** [comment]
As would I, but unfortunately I know from personal experience that this is not the case. 

That said, it's only my personal experience. It was massively detrimental to me, and hampered the development of [hass-hue-icons](https://github.com/arallsopp/hass-hue-icons) considerably, but I'm one person. 

Marius is better placed to answer for this repo. I believe it was originally intended to persist material icons that had been removed from the original source, but as I say, I'll leave it here.

**Comment by Mariusthvdb** [comment]
fully in agreement with Andy here, I'd rather keep my repo as pure as possible, with all carefully acknowledged and agreed authors of the icons in the repo.

Many of those are legacy Material Design icons, and can not be transferred at all I would think without their explicit consent (which was granted me personally by all of the mentioned MDI authors. 
Many others have been especially created for this repo (by Andy ea), and I would not want to have any issues because of that.

Not being a designer myself, I really feel for the contributors need for credit, and the mentioned repo has time and time again not honored that.

Hope you understand.
thanks for having a look here, and looking forward to other suggestions/contributions you might have!

**Comment by kaizersoje** [comment]
Thanks @Mariusthvdb. I appreciate all the work you and the other authors have done in ensuring all work is properly acknowledged.
